FROM golang:1.23 as builder

# Create a directory for the app in the container
# Following commands will be executed in this directory
WORKDIR /app

# Copy the go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o wolf .

# Run the app
CMD ["./wolf"]
